### ISSUE TITLE
php: Warning when installing ...

### ISSUE THREAD

**Issue by fenix011** [DurableDrupal/durable-drupal-distro#1]
from drush command,

```
# drush site-install drupallean --db-url='mysql://root:foo@localhost/drupallean' --site-name=Drupal_Lean
...
You are about to create a sites/default/files directory and create a sites/default/settings.php file and CREATE  the 'drupallean' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a few seconds ...                                                                                [ok]
WD php: Warning: Invalid argument supplied for foreach() in _features_restore() (line 970 of                                              [warning]
/var/www/html/durable-drupal-distro/sites/all/modules/contrib/features/features.module).
```

**Comment by victorkane** [comment]
Yes, the install profile doesn't have any features, so there is a null argument. In the next release, I'll put in a check to see if zero features are being reverted. Thanks!

**Comment by fenix011** [comment]
Ah! ... does it means that if there are 'Featured' modules coming in... they will be automatically reverted in DrupalLean ?  That would be great ! Am i wrong saying so ?

**Comment by victorkane** [comment]
Yes, you are correct! At the bottom of `drupallean.install` there is:

```
features_revert($features);
```

But it should not be called on a null array, as is the case now.

I will include a couple of features in the next release.

But, to tell you the truth, if there are many features, or they are complicated, sometimes you have to do a manual revert anyway. This is no problem, it can be done in the ansible playbook, which is actually perhaps a better place to put it. We'll see!
